---
title: "Simple document"
output: html_document
---

```{r include=FALSE}
# Load libraries
library(dplyr) # data wrangling
library(tidyr) # data wrangling
library(ggplot2) # data visualisation
library(sf) # simple features - geospatial geometries
library(osmdata) # obtaining OpenStreetMap vector data
library(units) # working with units
library(mapview) # interactive geometry viewing
library(ggmap) # downloading raster maps from a variety of sources
library(ggspatial) # map backgrounds and annotations for ggplot
library(tmap) # static/interactive map library with ggplot-like syntax
library(sp)
require(maps)
library(maptools)
```


```{r}
data1 = read_sf('mtbs_perimeter_data/mtbs_perims_DD.shp')
data_test = data1[,-c(2,22)]

crs_nad83 <- st_crs("+init=epsg:4269 +proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0") 

fire_ca = data_test %>% 
  rename("long" = BurnBndLon,
         "lat" = BurnBndLat) %>% 
  mutate(long = as.numeric(long),
         lat = as.numeric(lat)) %>% 
  st_transform(crs = crs_nad83)

wells_1 = readr::read_csv('./wells/States/California/CA_Alemeda_Sutter.csv')
wells_2 = readr::read_csv('./wells/States/California/CA_Tehama_Yuba.csv')

wells_ca = rbind(wells_1, wells_2)
wells_ca = wells_ca %>% 
  rename('long' = `Surface Hole Longitude (WGS84)`,
         'lat' = `Surface Hole Latitude (WGS84)`)

# Shapefile for wells in ca (geometry included)
wells_ca_sf = wells_ca %>% 
  drop_na(long,lat) %>% 
  st_as_sf(coords = c('long','lat'),
           crs = crs_nad83)


#usa_shp = read_sf('cb_2018_us_aiannh_500k/cb_2018_us_aiannh_500k.shp')

#ggplot() + 
  #geom_sf(data = data_test)

#ggplot(data_test)+ geom_sf(aes(fill = Incid_Type)) + theme_bw()

#plot(usa_shp)

#plot(usa_shp, reset = FALSE)
#plot(data_test, add = TRUE, col = 'red')

#plot(data_test['Incid_Type'], reset = FALSE)
#plot(usa_shp, add = TRUE, col = 'red')

sf::sf_use_s2(FALSE)
ca_inters = st_intersection(st_make_valid(fire_ca), st_make_valid(wells_ca_sf)) # 25404 rows
ca_inters %>% 
  filter_at(vars(ends_with("date")), any_vars(. < Ig_Date)) # 16385 rows

fire_ca_3338 = fire_ca %>% 
  st_as_sf() %>% 
  st_transform(3338)
fire_ca_buff = st_buffer(fire_ca_3338, 1000)

wells_3338 = wells_ca_sf %>% 
  st_transform(3338)
ca_inter_buff = st_intersection(fire_ca_buff, wells_3338) # 64692 rows
ca_inter_buff %>% 
  filter_at(vars(ends_with("date")), any_vars(. < Ig_Date)) # 41656


# All wells existed before 1984
wells_before_1984 = wells_3338 %>% 
  filter_at(vars(ends_with("date")), any_vars(. < "1985-01-01")) # 17579 wells 

fire_1984 = fire_ca_buff %>% 
  filter(Ig_Date < "1985-01-01" & Ig_Date > "1983-12-31")

# All wells existed before 2020
wells_before_2020 = wells_3338 %>% 
  filter_at(vars(ends_with("date")), any_vars(. < "2021-01-01")) # 21372 wells

fire_2020 = fire_ca_buff %>%  # 64 fires
  filter(Ig_Date < "2021-01-01" & Ig_Date > "2019-12-31")

intersection_2020 = st_intersection(wells_before_2020, fire_2020)
intersection_1984 = st_intersection(wells_before_1984, fire_1984)

unique(intersection_2020$Well.Name)
unique(intersection_1984$Well.Name) # 244 unique wells for 1984. 

max(fire_ca$Ig_Date)
```


## A function to turn longlat to country names
```{r}
library(sp)
library(rworldmap)

# The single argument to this function, points, is a data.frame in which:
#   - column 1 contains the longitude in degrees
#   - column 2 contains the latitude in degrees
coords2country = function(points)
{  
  countriesSP <- getMap(resolution='low')
  #countriesSP <- getMap(resolution='high') #you could use high res map from rworldxtra if you were concerned about detail

  # convert our list of points to a SpatialPoints object

  # pointsSP = SpatialPoints(points, proj4string=CRS(" +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))

  #setting CRS directly to that from rworldmap
  pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  


  # use 'over' to get indices of the Polygons object containing each point 
  indices = over(pointsSP, countriesSP)

  # return the ADMIN names of each country
  indices$ADMIN  
  #indices$ISO3 # returns the ISO3 code 
  #indices$continent   # returns the continent (6 continent model)
  #indices$REGION   # returns the continent (7 continent model)
}

longlat1 = data_test[,8:9]
longlat = longlat1 %>% 
  select(c(long, lat))

longlat = st_set_geometry(longlat, NULL)
coords2country(longlat)
data_test["country_names"] = coords2country(longlat)
```


## A function to turn longlat to county names
```{r}
# The single argument to this function, pointsDF, is a data.frame in which:
#   - column 1 contains the longitude in degrees (negative in the US)
#   - column 2 contains the latitude in degrees

lonlat_to_state_sp <- function(pointsDF) {
    # Prepare SpatialPolygons object with one SpatialPolygon
    # per state (plus DC, minus HI & AK)
    states <- map('county', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(states$names, ":"), function(x) x[1])
    states_sp <- map2SpatialPolygons(states, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Convert pointsDF to a SpatialPoints object 
    pointsSP <- SpatialPoints(pointsDF, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))

    # Use 'over' to get _indices_ of the Polygons object containing each point 
        indices <- over(pointsSP, states_sp)

    # Return the state names of the Polygons object containing each point
    stateNames <- sapply(states_sp@polygons, function(x) x@ID)
    stateNames[indices]
}
lonlat_to_state_sp(longlat)
data_test["county_names"] = lonlat_to_state_sp(longlat)

```

## Filter sf data by country and county
```{r}
data_test = filter(data_test, country_names == "United States of America")
data_test = data_test[,-22]
data_test$county_names = as.character(data_test$county_names)
unique(data_test$county_names)
data_CA = filter(data_test, grepl('california', county_names)) #ONLY CA counties
```

## Wells dataframe

```{r}
wells_df = read.csv("Wells Table CA.csv")

wells_df$County.Parish = as.character(wells_df$County.Parish)

levels(wells_df$County.Parish)

wells_df$County.Parish[wells_df$County.Parish=="ALAMEDA (CA)"] <- "california,alameda"
wells_df$County.Parish[wells_df$County.Parish=="COLUSA (CA)"] <- "california,colusa"
wells_df$County.Parish[wells_df$County.Parish=="FRESNO (CA)"] <- "california,fresno"
wells_df$County.Parish[wells_df$County.Parish=="IMPERIAL (CA)"] <- "california,imperial"
wells_df$County.Parish[wells_df$County.Parish=="KINGS (CA)"] <- "california,kings"
wells_df$County.Parish[wells_df$County.Parish=="LOS ANGELES (CA)"] <- "california,los angeles"
wells_df$County.Parish[wells_df$County.Parish=="MARIN (CA)"] <- "california,marin"
wells_df$County.Parish[wells_df$County.Parish=="MORRO BAY (CA)"] <- "california,morro bay"
wells_df$County.Parish[wells_df$County.Parish=="ORANGE (WATERS) (CA)"] <- "california,orange waters"
wells_df$County.Parish[wells_df$County.Parish=="POINT ARENA ZONE2 (CA)"] <- "california,point arena zone2"
wells_df$County.Parish[wells_df$County.Parish=="SAN BENITO (CA)"] <- "california,san benito"
wells_df$County.Parish[wells_df$County.Parish=="SAN DIEGO (WATERS) (CA)"] <- "california,san diego waters"
wells_df$County.Parish[wells_df$County.Parish=="SAN LUIS OBISPO (CA)"] <- "california,san luis obispo"
wells_df$County.Parish[wells_df$County.Parish=="SANTA BARBARA (CA)"] <- "california,santa barbara"
wells_df$County.Parish[wells_df$County.Parish=="SANTA CLARA (CA)"] <- "california,santa clara"
wells_df$County.Parish[wells_df$County.Parish=="SANTA CRUZ ISLAND (CA)"] <- "california,santa cruz island"
wells_df$County.Parish[wells_df$County.Parish=="SIERRA (CA)"] <- "california,sierra"
wells_df$County.Parish[wells_df$County.Parish=="SOLANO (WATERS) (CA)"] <- "california,solano waters"
wells_df$County.Parish[wells_df$County.Parish=="SUTTER (CA)"] <- "california,sutter"
wells_df$County.Parish[wells_df$County.Parish=="VENTURA (CA)"] <- "california,ventura"
wells_df$County.Parish[wells_df$County.Parish=="YUBA (CA)"] <- "california,yuba"
wells_df$County.Parish[wells_df$County.Parish=="AMADOR (CA)"] <- "california,amador"
wells_df$County.Parish[wells_df$County.Parish=="CONTRA COSTA (CA)"] <- "california,contra costa"
wells_df$County.Parish[wells_df$County.Parish=="GLENN (CA)"] <- "california,san glenn"
wells_df$County.Parish[wells_df$County.Parish=="INYO (CA)"] <- "california,inyo"
wells_df$County.Parish[wells_df$County.Parish=="LAKE (CA)"] <- "california,lake"
wells_df$County.Parish[wells_df$County.Parish=="LOS ANGELES (WATERS) (CA)"] <- "california,los angeles waters"
wells_df$County.Parish[wells_df$County.Parish=="MENDOCINO (CA)"] <- "california,mendocino"
wells_df$County.Parish[wells_df$County.Parish=="MONO (CA)"] <- "california,mono"
wells_df$County.Parish[wells_df$County.Parish=="NAPA (CA)"] <- "california,napa"
wells_df$County.Parish[wells_df$County.Parish=="PLACER (CA)"] <- "california,placer"
wells_df$County.Parish[wells_df$County.Parish=="RIVERSIDE (CA)"] <- "california,riverside"
wells_df$County.Parish[wells_df$County.Parish=="SAN BERNARDINO (CA)"] <- "california,san bernardino"
wells_df$County.Parish[wells_df$County.Parish=="SAN FRANCISCO ZONE3 (CA)"] <- "california,san francisco zone3"
wells_df$County.Parish[wells_df$County.Parish=="SAN MATEO"] <- "california,san mateo"
wells_df$County.Parish[wells_df$County.Parish=="SANTA BARBARA (WATERS) (CA)"] <- "california,santa barbara waters"
wells_df$County.Parish[wells_df$County.Parish=="SANTA CRUZ (CA)"] <- "california,santa cruz"
wells_df$County.Parish[wells_df$County.Parish=="SANTA ROSA (CA)"] <- "california,santa rosa"
wells_df$County.Parish[wells_df$County.Parish=="SISKIYOU (CA)"] <- "california,siskiyou"
wells_df$County.Parish[wells_df$County.Parish=="SONOMA (CA)"] <- "california,sonoma"
wells_df$County.Parish[wells_df$County.Parish=="TEHAMA (CA)"] <- "california,tehama"
wells_df$County.Parish[wells_df$County.Parish=="VENTURA (WATERS) (CA)"] <- "california,ventura waters"
wells_df$County.Parish[wells_df$County.Parish=="BUTTE (CA)"] <- "california,butte"
wells_df$County.Parish[wells_df$County.Parish=="EUREKA ZONE 1 (CA)"] <- "california,eureka zone1"
wells_df$County.Parish[wells_df$County.Parish=="HUMBOLDT (CA)"] <- "california,humboldt"
wells_df$County.Parish[wells_df$County.Parish=="KERN (CA)"] <- "california,kern"
wells_df$County.Parish[wells_df$County.Parish=="LASSEN (CA)"] <- "california,lassen"
wells_df$County.Parish[wells_df$County.Parish=="MADERA (CA)"] <- "california,madera"
wells_df$County.Parish[wells_df$County.Parish=="MERCED (CA)"] <- "california,merced"
wells_df$County.Parish[wells_df$County.Parish=="MONTEREY (CA)"] <- "california,monterey"
wells_df$County.Parish[wells_df$County.Parish=="ORANGE (CA)"] <- "california,orange"
wells_df$County.Parish[wells_df$County.Parish=="PLUMAS (CA)"] <- "california,plumas"
wells_df$County.Parish[wells_df$County.Parish=="SACRAMENTO (CA)"] <- "california,sacramento"
wells_df$County.Parish[wells_df$County.Parish=="SAN DIEGO (CA)"] <- "california,los san diego"
wells_df$County.Parish[wells_df$County.Parish=="SAN JOAQUIN (CA)"] <- "california,san joaquin"
wells_df$County.Parish[wells_df$County.Parish=="SAN NICOLAS AREA (CA)"] <- "california,san nicolas area"
wells_df$County.Parish[wells_df$County.Parish=="SANTA CATALINA AREA (CA)"] <- "california,santa catalina area"
wells_df$County.Parish[wells_df$County.Parish=="SANTA CRUZ AREA (CA)"] <- "california,santa cruz area"
wells_df$County.Parish[wells_df$County.Parish=="SHASTA (CA)"] <- "california,shasta"
wells_df$County.Parish[wells_df$County.Parish=="SOLANO (CA)"] <- "california,solano"
wells_df$County.Parish[wells_df$County.Parish=="STANISLAUS (CA)"] <- "california,stanislaus"
wells_df$County.Parish[wells_df$County.Parish=="TULARE (CA)"] <- "california,tulare"
wells_df$County.Parish[wells_df$County.Parish=="YOLO (CA)"] <- "california,yolo"

names(wells_df)[names(wells_df) == 'County.Parish'] <- 'county_names'

#df_merged = inner_join(data_CA, wells_df, by = "county_names")


```


```{r}
ggplot(data_CA)+ geom_sf(aes(fill = Incid_Type)) + theme_bw()
#glimpse()
```

## Focus on Kern
```{r}
data_kern = filter(data_CA, county_names == "california,kern")
```

```{r}
library(tidyverse)
wells_df2 = wells_df[,colSums(is.na(wells_df))<10000]

crs_nad83 <- st_crs("+init=epsg:4269 +proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0") 

wells_sf = wells_df2 %>% 
  na.omit() %>% 
  st_as_sf(coords = c("Surface.Hole.Longitude..WGS84.", "Surface.Hole.Latitude..WGS84."),
           crs = crs_nad83)

wells_kern_sf = wells_sf %>% 
  filter(county_names == "california,kern")

ggplot(wells_kern_sf)+ geom_sf() + theme_bw()

kern_intersect = st_intersection(data_kern, wells_kern_sf[1:100,])

# Intersection of wells and wild fire in Kern produces 7082 rows of data.
ggplot() + geom_sf(data = sample_wells_1000) + geom_sf(data = data_kern) + theme_bw()

ggplot(data = data_kern) +
  geom_sf() +
  #coord_sf(xlim = c(-120.08, -118.395), ylim = c(35.016, 35.757), expand = FALSE) +
  coord_sf(xlim = c(-120.08, -118.7), ylim = c(34.839, 35.783)) +
  xlab("Longtidue") + ylab("Latitude") +
  ggtitle("Wells and Wild Fire in Kern") +
  geom_point(data = wells_kern, mapping = aes(x = Surface.Hole.Longitude..WGS84.,
                                              y = Surface.Hole.Latitude..WGS84.),
             colour = "black",
             shape = 4,
             size = 0.01,
             alpha = 0.1) +
  theme_bw() +
  geom_sf(data = data_kern, fill = NA, color = 'red')

kern_buff_3k = st_buffer(data_kern, 3000)

ggplot(data = kern_buff_3k) +
  geom_sf() +
  #coord_sf(xlim = c(-120.08, -118.395), ylim = c(35.016, 35.757), expand = FALSE) +
  coord_sf(xlim = c(-120.08, -118.7), ylim = c(34.839, 35.783)) +
  xlab("Longtidue") + ylab("Latitude") +
  ggtitle("Wells and Wild Fire in Kern") +
  geom_point(data = wells_kern, mapping = aes(x = Surface.Hole.Longitude..WGS84.,
                                              y = Surface.Hole.Latitude..WGS84.),
             colour = "black",
             shape = 4,
             size = 0.01,
             alpha = 0.1) +
  theme_bw() +
  geom_sf(data = data_kern, fill = NA, color = 'red')


```


## Leaflet zoomable map 
```{r}
library(leaflet)

layer1 <- data_kern %>% st_geometry()
layer2 <- wells_kern_sf %>% st_geometry()

map <- leaflet() %>%
  
  # adds grayscale basemap
  addProviderTiles(providers$OpenStreetMap) %>%
  
  # CalEnviroScreen percentile .............................................
  
  # adds 1st layer
  addPolygons(data         = layer1,
              weight       = 1, 
              color        = "white",
              fillColor    = "black",
              fill         = TRUE, 
              fillOpacity  = 0.1, 
              stroke       = TRUE,
              dashArray    = c(5,5), 
              smoothFactor = 3,
              options      = pathOptions(clickable = F),
              group        = "Wild Fire in Kern") %>%
  
  # adds 2nd layer
  addCircles( data         = layer2,
              weight       = 1, 
              color        = "white",
              fillColor    = "red",
              fill         = TRUE, 
              fillOpacity  = 0.2, 
              stroke       = TRUE,
              dashArray    = c(5,5), 
              options      = pathOptions(clickable = F),
              group        = "All Wells in Kern") %>%
  addMeasure(primaryLengthUnit   = "miles",
             secondaryLengthUnit = "kilometers", 
             primaryAreaUnit     = "acres",
             secondaryAreaUnit   = "hectares", 
             position            = "topleft") %>%
  
  # add layers control
  addLayersControl(
    overlayGroups = c("Wild Fire in Kern",
                      "Wells in Kern"),
    options = layersControlOptions(collapsed = FALSE),
    position = "topright") %>%
  
  # adds scale bar  
  addScaleBar(position = "topright") %>%
  
  # sets viewer and zoom level
  setView(lng = -120, lat = 37, zoom = 6)

map

```


```{r}
wells_LA_sf = wells_sf %>% 
  filter(county_names == "california,los angeles")

data_LA = filter(data_CA, county_names == "california,los angeles")

#ggplot(wells_LA_sf)+ geom_sf() + theme_bw()

sample_LA_1k = slice_sample(wells_LA_sf, n =10000)
sample_LA_1k = st_transform(sample_LA_1k, st_crs(data_LA))

sf::sf_use_s2(FALSE)

st_intersection(data_LA, wells_LA_sf) # 1059 rows
```

```{r}
site_df = read_csv("Site_data.CSV")
glimpse(site_df)

```

## Intersect and map site_df onto wild fire dataframe

```{r}
sites_kern = filter(site_df, county_parish == "KERN (CA)")

# first production date for sites in Kern ranges from 1977-01-01 to 2021-03-01
min(na.omit(sites_kern$first_prod_date))
max(na.omit(sites_kern$first_prod_date))

# first Ig_Date for wild fires in Kern ranges from 1984-05-26 to 2019-05-07
min(data_kern$Ig_Date)
max(data_kern$Ig_Date)


sites_kern_sf = sites_kern %>% 
  st_as_sf(coords = c("surface_hole_longitude_wgs84", "surface_hole_latitude_wgs84"),
           crs = crs_nad83)

# Intersection of sites and wildfire in Kern 
st_intersection(data_kern, sites_kern_sf) # 1009 rows


```

## Live map of sites and wildfire intersection 

```{r}

library(leaflet)

layer1 <- data_kern %>% st_geometry()
layer2 <- sites_kern_sf %>% st_geometry()

map <- leaflet() %>%
  
  # adds grayscale basemap
  addProviderTiles(providers$OpenStreetMap) %>%
  
  # CalEnviroScreen percentile .............................................
  
  # adds 1st layer
  addPolygons(data         = layer1,
              weight       = 1, 
              color        = "white",
              fillColor    = "black",
              fill         = TRUE, 
              fillOpacity  = 0.1, 
              stroke       = TRUE,
              dashArray    = c(5,5), 
              smoothFactor = 3,
              options      = pathOptions(clickable = F),
              group        = "Wild Fire in Kern") %>%
  
  # adds 2nd layer
  addCircles( data         = layer2,
              weight       = 1, 
              color        = "white",
              fillColor    = "red",
              fill         = TRUE, 
              fillOpacity  = 0.2, 
              stroke       = TRUE,
              dashArray    = c(5,5), 
              options      = pathOptions(clickable = F),
              group        = "All Sites in Kern") %>%
  addMeasure(primaryLengthUnit   = "miles",
             secondaryLengthUnit = "kilometers", 
             primaryAreaUnit     = "acres",
             secondaryAreaUnit   = "hectares", 
             position            = "topleft") %>%
  
  # add layers control
  addLayersControl(
    overlayGroups = c("Wild Fire in Kern",
                      "Sites in Kern"),
    options = layersControlOptions(collapsed = FALSE),
    position = "topright") %>%
  
  # adds scale bar  
  addScaleBar(position = "topright") %>%
  
  # sets viewer and zoom level
  setView(lng = -120, lat = 37, zoom = 6)

map

```

```{r}
#filter(sites_kern_sf, first_prod_date > 1984-05-26)
```

## Mar 1 
```{r}

# Get a list of dataframes, one for each county, indicating the wells in wild fire zone
get_intersection = function(name_in){
  fire = filter(data_CA, county_names == name_in)
  wells = filter(wells_sf, county_names == name_in)
  sf::sf_use_s2(FALSE)
  intersection = st_intersection(fire, wells)
  return(intersection)
}

county_list = c("california,siskiyou","california,shasta","california,trinity","california,mendocino",
                "california,tehama","california,colusa","california,lake","california,plumas",
                "california,inyo","california,lassen","california,modoc","california,san diego",
                "california,riverside","california,kern","california,tulare",
                "california,mono","california,calaveras","california,placer","california,mariposa",
                "california,los angeles","california,imperial","california,san bernardino","california,stanislaus",
                "california,fresno","california,san benito","california,glenn","california,san luis obispo",
                "california,butte","california,kings","california,merced",
                "california,orange","california,san joaquin","california,tuolumne",
                "california,solano","california,sonoma","california,yolo","california,santa clara",
                "california,alpine","california,sierra","california,nevada","california,del norte",
                "california,madera","california,humboldt","california,alameda","california,el dorado",
                "california,sacramento","california,marin","california,sutter","california,yuba",
                "california,contra costa","california,napa","california,amador","california,santa cruz")


df = sapply(county_list, get_intersection, simplify = FALSE)

# "california,monterey", california,santa barbara", ,"california,ventura"

```


```{r warning=FALSE}
# Get number of wells in wild-fire region by county
get_n_rows = function(name_in){
  fire = filter(data_CA, county_names == name_in)
  wells = filter(wells_sf, county_names == name_in)
  sf::sf_use_s2(FALSE)
  intersection = st_intersection(fire, wells)
  return(nrow(intersection))
}

sapply(county_list, get_n_rows, simplify = FALSE) # Number of intersections by county
```


```{r}
# returns the fire-well dataframes including 1km buffer zones
get_inter_buff = function(name_in){
  fire = st_as_sf(data_CA) %>% st_transform(3488)
  fire2 = filter(fire, county_names == name_in)
  fire_buff = st_buffer(fire2, 1000)
  wells_sf = wells_df2 %>% 
  na.omit() %>% 
  st_as_sf(coords = c("Surface.Hole.Longitude..WGS84.", "Surface.Hole.Latitude..WGS84."),
           crs = crs_nad83) %>% st_transform(3488)
  wells = filter(wells_sf, county_names == name_in)
  sf::sf_use_s2(FALSE)
  intersection = st_intersection(fire_buff, wells)
  return(intersection)
}

# Combined into a list of dataframes, one for each county
df_buff = sapply(county_list, get_inter_buff, simplify = FALSE)
```


```{r}
# computes the number of wells included in the 1km buffer zone
get_inter_buff_n = function(name_in){
  fire = st_as_sf(data_CA) %>% st_transform(3488)
  fire2 = filter(fire, county_names == name_in)
  fire_buff = st_buffer(fire2, 1000)
  wells_sf = wells_df2 %>% 
  na.omit() %>% 
  st_as_sf(coords = c("Surface.Hole.Longitude..WGS84.", "Surface.Hole.Latitude..WGS84."),
           crs = crs_nad83) %>% st_transform(3488)
  wells = filter(wells_sf, county_names == name_in)
  sf::sf_use_s2(FALSE)
  intersection = st_intersection(fire_buff, wells)
  return(nrow(intersection))
}

sapply(county_list, get_inter_buff_n, simplify = FALSE)
```


```{r}
# Brief summary 
no_buff = c(0,0,0,0,5,4,0,0,0,0,0,0,22,7082,13,0,0,0,0,1059,0,22,2,752,6,0,46,
            1,341,1,466,6,0,3,2,59,1,0,0,0,0,0,0,3,0,0,0,17,2,0,1,0,1)
buff_1km = c(0,0,0,0,15,5,0,0,0,1,0,0,67,23382,56,0,0,0,0,2432,0,82,10,4916,
             28,0,147,2,792,10,1577,16,0,16,4,133,2,0,0,0,0,1,2,6,0,0,0,78,2,
             1,1,0,2)
intersection_df = data.frame(county_list, no_buff, buff_1km)
```


```{r}

counties = c(rep("california,tehama",15), rep("california,colusa",5), "california,lassen",
           rep("california,riverside",67), rep("california,kern",23382), rep("california,tulare",56),
           rep("california,los angeles",2432), rep("california,san bernardino",82), rep("california,stanislaus",10),
           rep("california,fresno",4916), rep("california,san benito",28), rep("california,san luis obispo",147),
           rep("california,butte",2), rep("california,kings",792), rep("california,merced",10), rep("california,orange",1577),
           rep("california,san joaquin",16), rep("california,solano",16), rep("california,sonoma",4),
           rep("california,yolo",133), rep("california,santa clara",2), "california,madera", rep("california,humboldt",2),
           rep("california,alameda",6), rep("california,sutter",78), rep("california,yuba",2), "california,contra costa",
           "california,napa", rep("california,santa cruz",2))

# Number of wells after buffer 
wells_number_buff = c(rep(15,15), rep(5,5), 1,
           rep(67,67), rep(23382,23382), rep(56,56),
           rep(2432,2432), rep(82,82), rep(10,10),
           rep(4916,4916), rep(28,28), rep(147,147),
           rep(2,2), rep(792,792), rep(10,10), rep(1577,1577),
           rep(16,16), rep(16,16), rep(4,4),
           rep(133,133), rep(2,2), 1, rep(2,2),
           rep(6,6), rep(78,78), rep(2,2), 1,
           1, rep(2,2))

# Number of wells without buffering
wells_number = c(rep(5,15), rep(4,5), 1,
           rep(22,67), rep(7082,23382), rep(13,56),
           rep(1059,2432), rep(22,82), rep(2,10),
           rep(752,4916), rep(6,28), rep(46,147),
           rep(1,2), rep(341,792), rep(1,10), rep(466,1577),
           rep(6,16), rep(3,16), rep(2,4),
           rep(59,133), rep(1,2), 0, rep(0,2),
           rep(3,6), rep(17,78), rep(2,2), 0,
           1, rep(1,2))

# Find dates completed
find_date = function(x){
  date_x = x$Completion.Date %>% as.data.frame()
  dates = bind_rows(date_x)
  return(dates)
}

dates = purrr::map(df_buff, ~find_date(.))
dates_col = do.call("rbind", dates)[,1]

# Find geometry with buffer zone
find_geom = function(x){
  geom_x = x$geometry %>% as.data.frame()
  geom = bind_rows(geom_x)
  return(geom)
}

geom_col = purrr::map(df_buff, ~find_geom(.))
geom = do.call("rbind", geom_col)[,1]

# Find geometry no buffer zone
geom_col_nb = purrr::map(df, ~find_geom(.))
geom_nb = do.call("rbind", geom_col_nb)[,1]
geom_nb = geom_nb %>% st_as_sf() %>% st_transform(3488)

# Append all 
summ_df = data.frame(counties, dates_col, wells_number_buff, geom)
summ_sf = summ_df %>% st_as_sf()

```


```{r}
# Los Angeles
ggplot() + geom_sf(data = df_buff[["california,los angeles"]]) + 
  geom_sf(data = data_LA) + theme_bw()

# Fresno
ggplot() + geom_sf(data = df_buff[["california,fresno"]]) + 
  geom_sf(data = filter(data_CA, county_names == "california,fresno")) + theme_bw()

# Orange
ggplot() + geom_sf(data = df_buff[["california,orange"]]) + 
  geom_sf(data = filter(data_CA, county_names == "california,orange")) + theme_bw()

# Kings
ggplot() + geom_sf(data = df_buff[["california,kings"]]) + 
  geom_sf(data = filter(data_CA, county_names == "california,kings")) + theme_bw()
```







```{r}
library(leaflet)

crs_nad83 <- st_crs("+init=epsg:4269 +proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0") 

data_LA_leaflet = data_LA %>% 
  st_as_sf(coords = c("long", "lat"),
           crs = crs_nad83)

summ_sf_leaflet = summ_sf %>% 
  st_transform(crs = crs_nad83)

layer1 <- data_LA_leaflet %>% st_geometry()
layer2 <- summ_sf_leaflet %>% st_geometry()

map <- leaflet() %>%
  
  # adds grayscale basemap
  addProviderTiles(providers$OpenStreetMap) %>%
  
  # CalEnviroScreen percentile .............................................
  
  # adds 1st layer
  addPolygons(data         = layer1,
              weight       = 1, 
              color        = "white",
              fillColor    = "black",
              fill         = TRUE, 
              fillOpacity  = 0.1, 
              stroke       = TRUE,
              dashArray    = c(5,5), 
              smoothFactor = 3,
              options      = pathOptions(clickable = F),
              group        = "Wild Fire in LA") %>%
  
  # adds 2nd layer
  addCircles( data         = layer2,
              weight       = 1, 
              color        = "white",
              fillColor    = "red",
              fill         = TRUE, 
              fillOpacity  = 0.2, 
              stroke       = TRUE,
              dashArray    = c(5,5), 
              options      = pathOptions(clickable = F),
              group        = "Wells in LA with Buffer") %>%
  addMeasure(primaryLengthUnit   = "miles",
             secondaryLengthUnit = "kilometers", 
             primaryAreaUnit     = "acres",
             secondaryAreaUnit   = "hectares", 
             position            = "topleft") %>%
  
  # add layers control
  addLayersControl(
    overlayGroups = c("Wild Fire in LA",
                      "Wells in LA with Buffer"),
    options = layersControlOptions(collapsed = FALSE),
    position = "topright") %>%
  
  # adds scale bar  
  addScaleBar(position = "topright") %>%
  
  # sets viewer and zoom level
  setView(lng = -120, lat = 37, zoom = 6)

map

```


```{r}
# Filter the dates. If a well's completion date is after the Ig date (wildfire date), drop it
filter_date = function(df_in){
  res = df_in %>% 
    rowwise() %>% 
    filter(Completion.Date < Ig_Date) %>% 
    ungroup()
  return(res)
}

wells_sf2 = wells_sf %>% 
  filter(!county_names %in% c("california,monterey", "california,santa barbara", "california,ventura"))
st_intersection(data_CA, wells_sf2)
```

